columns:
  - url: object
  - length_url: int64
  - length_hostname: int64
  - ip: int64
  - nb_dots: int64
  - nb_hyphens: int64
  - nb_at: int64
  - nb_qm: int64
  - nb_and: int64
  - nb_or: int64
  - nb_eq: int64
  - nb_underscore: int64
  - nb_tilde: int64
  - nb_percent: int64
  - nb_slash: int64
  - nb_star: int64
  - nb_colon: int64
  - nb_comma: int64
  - nb_semicolumn: int64
  - nb_dollar: int64
  - nb_space: int64
  - nb_www: int64
  - nb_com: int64
  - nb_dslash: int64
  - http_in_path: int64
  - https_token: int64
  - ratio_digits_url: float64
  - ratio_digits_host: float64
  - punycode: int64
  - port: int64
  - tld_in_path: int64
  - tld_in_subdomain: int64
  - abnormal_subdomain: int64
  - nb_subdomains: int64
  - prefix_suffix: int64
  - random_domain: int64
  - shortening_service: int64
  - path_extension: int64
  - nb_redirection: int64
  - nb_external_redirection: int64
  - length_words_raw: int64
  - char_repeat: int64
  - shortest_words_raw: int64
  - shortest_word_host: int64
  - shortest_word_path: int64
  - longest_words_raw: int64
  - longest_word_host: int64
  - longest_word_path: int64
  - avg_words_raw: float64
  - avg_word_host: float64
  - avg_word_path: float64
  - phish_hints: int64
  - domain_in_brand: int64
  - brand_in_subdomain: int64
  - brand_in_path: int64
  - suspecious_tld: int64
  - statistical_report: int64
  - nb_hyperlinks: int64
  - ratio_intHyperlinks: float64
  - ratio_extHyperlinks: float64
  - ratio_nullHyperlinks: int64
  - nb_extCSS: int64
  - ratio_intRedirection: int64
  - ratio_extRedirection: float64
  - ratio_intErrors: int64
  - ratio_extErrors: float64
  - login_form: int64
  - external_favicon: int64
  - links_in_tags: float64
  - submit_email: int64
  - ratio_intMedia: float64
  - ratio_extMedia: int64
  - sfh: float64
  - iframe: int64
  - popup_window: int64
  - safe_anchor: int64
  - onmouseover: int64
  - right_clic: int64
  - empty_title: int64
  - domain_in_title: int64
  - domain_with_copyright: int64
  - whois_registered_domain: int64
  - domain_registration_length: int64
  - domain_age: int64
  - web_traffic: int64
  - dns_record: int64
  - google_index: int64
  - page_rank: int64
  - status: object

numerical_columns:
  - length_url
  - length_hostname
  - ip
  - nb_dots
  - nb_hyphens
  - nb_at
  - nb_qm
  - nb_and
  - nb_or
  - nb_eq
  - nb_underscore
  - nb_tilde
  - nb_percent
  - nb_slash
  - nb_star
  - nb_colon
  - nb_comma
  - nb_semicolumn
  - nb_dollar
  - nb_space
  - nb_www
  - nb_com
  - nb_dslash
  - http_in_path
  - https_token
  - ratio_digits_url
  - ratio_digits_host
  - punycode
  - port
  - tld_in_path
  - tld_in_subdomain
  - abnormal_subdomain
  - nb_subdomains
  - prefix_suffix
  - random_domain
  - shortening_service
  - path_extension
  - nb_redirection
  - nb_external_redirection
  - length_words_raw
  - char_repeat
  - shortest_words_raw
  - shortest_word_host
  - shortest_word_path
  - longest_words_raw
  - longest_word_host
  - longest_word_path
  - avg_words_raw
  - avg_word_host
  - avg_word_path
  - phish_hints
  - domain_in_brand
  - brand_in_subdomain
  - brand_in_path
  - suspecious_tld
  - statistical_report
  - nb_hyperlinks
  - ratio_intHyperlinks
  - ratio_extHyperlinks
  - ratio_nullHyperlinks
  - nb_extCSS
  - ratio_intRedirection
  - ratio_extRedirection
  - ratio_intErrors
  - ratio_extErrors
  - login_form
  - external_favicon
  - links_in_tags
  - submit_email
  - ratio_intMedia
  - ratio_extMedia
  - sfh
  - iframe
  - popup_window
  - safe_anchor
  - onmouseover
  - right_clic
  - empty_title
  - domain_in_title
  - domain_with_copyright
  - whois_registered_domain
  - domain_registration_length
  - domain_age
  - web_traffic
  - dns_record
  - google_index
  - page_rank

